### ISSUE TITLE
Issue with digital miner and the auto-eject button

### ISSUE THREAD

**Issue by kragnoth** [mekanica/mekanica#112] opened 2019-03-24 16:44 UTC
https://github.com/mekanism-mod/Mekanism/issues/5324

This issue happens in base mekanism as well.  The auto-eject button does not function as intended.

If you have ores in your machine and you hit auto-eject, it will eject that number of ores every time it mines one ore.  You could theoretically mine 64 gold every time you mine a single ore.

The ores also never leave the mechanical miner.

I will try and duplicate this with a vanilla chest, but it definitely happens with AA crates.

**Comment by kragnoth** [comment] 2019-03-24 16:45
looks like a duplicate of https://github.com/mekanica/mekanica/issues/102, sorry

**Comment by pupnewfster** [comment] 2019-03-24 16:45
Duplicate of #102 we hopefully with have a fix out later today of this. I am mainly just working up on cleaning up #106 a little which fixes it.

**Closed by pupnewfster** 2019-03-24 16:45 UTC
Labels: Duplicate

**Comment by pupnewfster** [comment] 2019-03-24 22:45
Fixed in 1.1.2 btw (not quite sure how notifications go through as this is a duplicate and not linked directly)
